PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/cf1180e7f1d5ca7991bcf2e01aa4ecb9fd4582c2

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (6c76f99fe5018d1335d544a532aa15c9eafccc59)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...cf1180e7f1d5ca7991bcf2e01aa4ecb9fd4582c2

cf1180e7f1 (HEAD, origin/master) boards: sabre-6quad: Add QEMU instructions to README.txt
10721c0826 Kconfig: Move the ARCH_PHY_INTERRUPT option to net/Kconfig and make it unconditionally selectable.
04128b4570 arch/sim/src: Rename board_lcd.c to up_lcd.c like other sim code
3cb259daa6 drivers/Kconfig:  Move if/endif to subfolder Kconfig
fa3e66fe82 arch/sim/src/:  Reimplement sim uart on top of serial driver framework
6d69439f58 Call xxx_timer_initialize from clock subsystem
76bbed07a4 Call up_irqinitialize from irq subsystem
48f1793a60 tools/testbuild.sh: make sure fail get the real return error value
a8de37fbec Ensure all source code end with one and only one newline
81f1133174 ELF64 support (#220)

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/d2e1c8a4f3cb5df7702536b13513f886d7cf141d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (6c76f99fe5018d1335d544a532aa15c9eafccc59)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...d2e1c8a4f3cb5df7702536b13513f886d7cf141d

d2e1c8a4 (HEAD -> master, origin/master) apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m
2f4b309b gs2200m: Retry indefinately on GS2200M_IOC_ASSOC failure
e738fbed graphics/littlevgl/Makefile: update lvgl.h dependency to fix parallel build break
bb3cd0a4 apps: elf: Fix stack corruption in task test
bf3e6e23 Improvements for telnet server